version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cleverbooks-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: cleverbooks-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

volumes:
  mongodb_data:
